### ISSUE TITLE
Player gets kicked from server and can't re-join after equipping Skyseeker's pickaxe

### ISSUE THREAD

**Issue by riskable** [Ellpeck/NaturesAura#123]
If I start a new server, join, then give myself a Skyseeker's pickaxe (I'm an op just testing things out) I can use it fine *for a bit* but after mining some stuff and getting other things into my hotbar I get booted from the server.  It gives the following error:

```
[14:36:14] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /10.1.1.3:34480
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:424) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:entity_sync.MixinServerPlayerEntity,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinServerPlayerEntity_MA,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,xf:fml:backpacked:creative_inventory_action_fix,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:alternate_dimension.MixinServerPlayNetworkHandler_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:position_sync.MixinServerPlayNetworkHandler,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:alternate_dimension/MixinServerPlayNetworkHandler_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:block_manipulation/MixinServerPlayNetworkHandler_B,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:lightoverlay-forge:light-overlay-forge,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.func_174872_o()I
        at de.ellpeck.naturesaura.items.tools.ItemPickaxe.func_77663_a(ItemPickaxe.java:81) ~[?:28.1] {re:classloading}
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:charm:ItemStack,xf:fml:quark:add-spacing-for-stack,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity,xf:fml:backpacked:player_init_hook,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:alternate_dimension.MixinPlayerEntity_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:LivingEntity.playFallSound,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:block_manipulation.MixinLivingEntity,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:collision.MixinLivingEntity_C,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity,xf:fml:backpacked:player_init_hook,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:alternate_dimension.MixinPlayerEntity_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:entity_sync.MixinServerPlayerEntity,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinServerPlayerEntity_MA,pl:mixin:A}
        ... 8 more
```

I don't know if it's a conflict with Immersive Portals por backpacked or any of the other mods mentioned in that error.  All I know is it only seems to happen when I switch from something else in my hotbar over to the Skyseeker's pickaxe.

This is with Forge 31.2.2 and Nature's Aura 28.1

**Comment by eplossl** [comment]
I ran into the same problem this morning in the New Beginnings modpack by Haydennz.  This includes Minecraft Version: 1.15.2 (modded) forge-31.2.0 and is using Nature's aura 28.1 as well.  I don't see an update available in Twitch just yet, but that's ok since I see that it looks like you just fixed it yesterday.  In my case, the problem was that I built the pick, and the first time I tried to use it, I broke a block and the game crashed out with an error similar to the one above:

 [12:19:13] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /47.222.30.124:62396
net.minecraft.crash.ReportedException: Ticking player
at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:424) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:A}
at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.func_174872_o()I
at de.ellpeck.naturesaura.items.tools.ItemPickaxe.func_77663_a(ItemPickaxe.java:81) ~[?:28.1] {re:classloading}
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:quark:add-spacing-for-stack,pl:runtimedistcleaner:A}

Since then, I can't log back in.
