### ISSUE TITLE
Ticking decay crashing server

### ISSUE THREAD

**Issue by x543g** [Ellpeck/NaturesAura#149]
After I planted some trees that remove bad aura, this happened and the server keeps crashing :(
`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 18/10/20 8:55 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=persistent, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{naturesaura:decayed_leaves}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:classloading}
	at de.geheimagentnr1.rapid_leaf_decay.decayer.DecayWorker.calculateDistances(DecayWorker.java:75) ~[?:1.0.0] {re:classloading}
	at de.geheimagentnr1.rapid_leaf_decay.decayer.DecayWorker.doWork(DecayWorker.java:48) ~[?:1.0.0] {re:classloading}
	at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_511_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:824) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}`

**Comment by yabkeno** [comment]
1.16.3 version, version 31.0 for NA

**Comment by Ellpeck** [comment]
This is an issue with rapid_leaf_decay, which assumes that all blocks that return true on `isLeaves` also extend `LeavesBlock`.
