### ISSUE TITLE
Nature's Aura not seeing Patchouli

### ISSUE THREAD

**Issue by TobiDoesMC** [Ellpeck/NaturesAura#158]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- MOD naturesaura --
Details:
	Mod File: NaturesAura-31.0.jar
	Failure message: Mod naturesaura requires patchouli 1.1-23 or above
		Currently, patchouli is not installed
	Mod Version: 31.0
	Mod Issue URL: https://github.com/Ellpeck/NaturesAura
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.3-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.25-launcher.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1911940840 bytes (1823 MB) / 4762632192 bytes (4542 MB) up to 10379853824 bytes (9899 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx11136m
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.25
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.25-client.jar Minecraft {minecraft@1.16.3 NONE}
		torchmaster-2.3.4-alpha.jar Torchmaster {torchmaster@2.3.4-alpha NONE}
		nomowanderer_MC1.16.3_1.0.jar NoMoWanderer {nomowanderer@1.16.3_1.0 NONE}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta NONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 NONE}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 NONE}
		jei-1.16.3-7.6.0.49.jar Just Enough Items {jei@7.5.0.43 NONE}
		goblintraders-1.2.2-1.16.3.jar Goblin Traders {goblintraders@1.2.2 NONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 NONE}
		caelus-forge-1.16.3-2.0.0.3.jar Caelus API {caelus@1.16.3-2.0.0.3 NONE}
		colytra-forge-1.16.3-5.0.0.1.jar Colytra {colytra@1.16.3-5.0.0.1 NONE}
		betconduitpl_1.16.3_1.1.jar Better Conduit Placement {betconduitpl@1.1 NONE}
		rats-7.0.0-1.16.3.jar Rats {rats@7.0.0 NONE}
		collective-1.16.3-1.53.jar Collective {collective@1.53 NONE}
		ReAuth-1.16-Forge-3.9.2.jar ReAuth {reauth@3.9.2 NONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 NONE}
		Corail-Recycler-Mod-1.16.3.jar Corail Recycler {corail_recycler@1.0 NONE}
		citadel-1.4.1.jar Citadel {citadel@1.4.1 NONE}
		[1.16.3]+SecurityCraft+v1.8.20.1.jar SecurityCraft {securitycraft@v1.8.20.1 NONE}
		torcherino-13.0.0+1.16.3.jar Torcherino {torcherino@13.0.0 NONE}
		StorageDrawers-1.16.3-8.2.0.jar Storage Drawers {storagedrawers@8.2.0 NONE}
		betbeacpl_1.16.3_1.1.jar Better Beacon Placement {betbeacpl@1.1 NONE}
		jumbofurnace-1.16.3-2.1.0.0.jar Jumbo Furnace {jumbofurnace@1.16.3-2.1.0.0 NONE}
		ftb-ultimine-1603.1.1.12.jar FTB Ultimine {ftbultimine@1603.1.1.12 NONE}
		charginggadgets-1.3.0.jar Charging Gadgets {charginggadgets@1.3.0 NONE}
		ExtraStorage-1.16.3-1.1.0.jar Extra Storage {extrastorage@1.1.0 NONE}
		NaturesAura-31.0.jar Nature's Aura {naturesaura@31.0 NONE}
		nhacampfire_1.16.3-3.0.jar No Hostiles Around Campfire {nhacampfire@3.0 NONE}
		mcws-roofs-1.16.3-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 NONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 NONE}
		iceandfire-2.1.0-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 NONE}
		mininggadgets-1.6.0.jar Mining Gadgets {mininggadgets@1.6.0 NONE}
		immersive-portals-0.5-mc1.16.3-forge.jar Immersive Portals {immersive_portals@0.5 NONE}
		extradisks-1.16.2-1.3.1.jar Extra Disks {extradisks@1.3.1 NONE}
		forge-1.16.3-34.1.25-universal.jar Forge {forge@34.1.25 NONE}
		HearthstoneMod-1.16.3-0.5.2.jar Hearthstone Mod {hearthstonemod@1.16.3-0.5.2 NONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 NONE}
		refinedstorage-1.9.7.jar Refined Storage {refinedstorage@1.9.7 NONE}
		ratlantis-1.0.0-1.16.3.jar Rats: Ratlantis {ratlantis@1.0.0-1.16.3 NONE}
[https://imgur.com/a/AzboUtD](url)

**Comment by TobiDoesMC** [comment]
the link shows Patchouli is installed i took a screenshot

**Comment by Ellpeck** [comment]
Can you try with this version? https://ci.ellpeck.de/job/NaturesAura/job/main/7/artifact/build/libs/NaturesAura-32.0.7.jar
