### ISSUE TITLE
Alter Crash

### ISSUE THREAD

**Issue by schnipdip** [Ellpeck/NaturesAura#175]
Game crashes when right clicking the altar.

**
![image](https://user-images.githubusercontent.com/23109762/103844615-34f19300-5068-11eb-9019-1b60c74fd2aa.png)
**

Replication:

Right click on Nature Altar

Crash Report:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/6/21 9:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.crafting.RecipeManager.calcHash(RecipeManager.java:594) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:item.RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.handler$zbb000$OngetRecipes(RecipeManager.java:569) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:item.RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:item.RecipeManagerMixin,pl:mixin:A}
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar.getRecipeForInput(TileEntityNatureAltar.java:207) ~[?:28.5] {re:classloading}
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar.access$100(TileEntityNatureAltar.java:32) ~[?:28.5] {re:classloading}
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar$2.canInsert(TileEntityNatureAltar.java:49) ~[?:28.5] {re:classloading}
	at de.ellpeck.naturesaura.blocks.tiles.ItemStackHandlerNA.insertItem(ItemStackHandlerNA.java:48) ~[?:28.5] {re:classloading}
	at de.ellpeck.naturesaura.Helper.putStackOnTile(Helper.java:146) ~[?:28.5] {re:classloading}
	at de.ellpeck.naturesaura.blocks.BlockNatureAltar.func_225533_a_(BlockNatureAltar.java:60) ~[?:28.5] {re:classloading}
	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:269) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphor.mixins.json:block.MixinBlockState,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:287) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.47.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/426792528.call(Unknown Source) [forge-1.15.2-31.2.47.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.item.crafting.RecipeManager.calcHash(RecipeManager.java:594)
	at net.minecraft.item.crafting.RecipeManager.handler$zbb000$OngetRecipes(RecipeManager.java:569)
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java)
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar.getRecipeForInput(TileEntityNatureAltar.java:207)
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar.access$100(TileEntityNatureAltar.java:32)
	at de.ellpeck.naturesaura.blocks.tiles.TileEntityNatureAltar$2.canInsert(TileEntityNatureAltar.java:49)
	at de.ellpeck.naturesaura.blocks.tiles.ItemStackHandlerNA.insertItem(ItemStackHandlerNA.java:48)
	at de.ellpeck.naturesaura.Helper.putStackOnTile(Helper.java:146)
	at de.ellpeck.naturesaura.blocks.BlockNatureAltar.func_225533_a_(BlockNatureAltar.java:60)
	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:269)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:287)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['schnipdip'/547828, l='MpServer', x=-389.69, y=63.00, z=-46.91]]
	Chunk stats: Client Chunk Cache: 441, 240
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -591492357813092352
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,78,64), Chunk: (at 0,4,0 in 0,4; contains blocks 0,0,64 to 15,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20047119 game time, 107269 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/426792528.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3274875424 bytes (3123 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.47.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.47
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 DONE}
		strawgolem-1.15.2-1.9.jar Straw Golem {strawgolem@1.15.2-1.9 DONE}
		essentials-1.15.2-2.7.4.jar Essentials {essentials@1.15.2-2.7.4 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		NamePain-1.3.0_Forge-1.15.2.jar Name Pain {namepain@1.3.0 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		PackMenu-1.15.2-1.2.8.jar Pack Menu {packmenu@1.2.8 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		FarmersDelight-1.15.2-0.2.4b.jar Farmer's Delight {farmersdelight@1.15.2-0.2.4b DONE}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.6.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		mcw-trapdors-1.0.0fix-mc1.15.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 DONE}
		SilentGear-1.15.2-1.11.3+160.jar Silent Gear {silentgear@1.11.3+160 DONE}
		simplefarming-1.15.2-1.3.3.jar Simple Farming {simplefarming@1.15.1-1.3.3 DONE}
		MysticalAdaptations-1.15.2-1.2.3.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 DONE}
		NaturesAura-28.5.jar Nature's Aura {naturesaura@28.5 DONE}
		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		cc-tweaked-1.15.2-1.94.0.jar CC: Tweaked {computercraft@1.94.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.3.10.jar The Bumblezone {the_bumblezone@1.15.2-1.3.10 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		mining-helmet-1.15.2-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		FallingTree-1.15.2-2.4.0.jar Falling Tree {falling_tree@2.4.0 DONE}
		fishtraps-forge-1.15.2-0.0.5.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		KiwiBirds 1.3 1.15.2.jar Kiwi Birds {kiwibirds@1.2 1.15.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.6.0.jar Fruit Trees {fruittrees@1.6.0 DONE}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 DONE}
		VanillaTweaks-1.15.2.1.5.30.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.30 DONE}
		DefaultSettings-1.14.x-1.15.2-2.2.0.jar DefaultSettings {defaultsettings@2.2.0 DONE}
		betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		useful_railroads-1.15.2-1.4.2.29.jar Useful Railroads {usefulrailroads@1.4.2.29 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 DONE}
		JAOPCA-1.15.2-3.2.0.15.jar JAOPCA {jaopca@3.2.0.15 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-3.11m.jar Performant {performant@3.11m DONE}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		byg-1.0.11.jar Oh The Biomes You'll Go {byg@1.0.11 DONE}
		Aquaculture-1.15.2-2.0.21.jar Aquaculture 2 {aquaculture@1.15.2-2.0.21 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Patchouli open book context: n/a
	Launched Version: 1.15.2-forge-31.2.47
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
```

**Comment by schnipdip** [comment]
There is an issue with the Performant mod.
