### ISSUE TITLE
Ritual of the the forset

### ISSUE THREAD

**Issue by gogoetom** [Ellpeck/NaturesAura#191]
made the ritual of the forest and set it up for the ancient tree but the sapling won't grow used stacks of bone meal too anyone know whats the problem?
Using the new beginning mod pack

**Comment by gogoetom** [comment]
Crash


---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/7/21 7:52 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.item.crafting.RecipeManager.calcHash(RecipeManager.java:594) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.handler$zzn000$OngetRecipes(RecipeManager.java:569) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at de.ellpeck.naturesaura.blocks.BlockWoodStand.onTreeGrow(BlockWoodStand.java:76) ~[?:28.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_599_BlockWoodStand_onTreeGrow_SaplingGrowTreeEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.saplingGrowTree(ForgeEventFactory.java:701) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.SaplingBlock.func_226942_a_(SaplingBlock.java:43) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.SaplingBlock.func_225534_a_(SaplingBlock.java:34) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.Block.func_225542_b_(Block.java:445) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_227034_b_(BlockState.java:253) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphor.mixins.json:block.MixinBlockState,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:479) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderThreadsMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:340) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderThreadsMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.item.crafting.RecipeManager.calcHash(RecipeManager.java:594)
	at net.minecraft.item.crafting.RecipeManager.handler$zzn000$OngetRecipes(RecipeManager.java:569)
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java)
	at de.ellpeck.naturesaura.blocks.BlockWoodStand.onTreeGrow(BlockWoodStand.java:76)
	at net.minecraftforge.eventbus.ASMEventHandler_599_BlockWoodStand_onTreeGrow_SaplingGrowTreeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.saplingGrowTree(ForgeEventFactory.java:701)
	at net.minecraft.block.SaplingBlock.func_226942_a_(SaplingBlock.java:43)
	at net.minecraft.block.SaplingBlock.func_225534_a_(SaplingBlock.java:34)
	at net.minecraft.block.Block.func_225542_b_(Block.java:445)
	at net.minecraft.block.BlockState.func_227034_b_(BlockState.java:253)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:479)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:697)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:340)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['MariusNinjai'/297, l='King', x=-229.87, y=68.45, z=-4.36]]
	Chunk stats: ServerChunkCache: 3115
	Level dimension: DimensionType{minecraft:overworld}
	Level name: King
	Level seed: -1259299250802944798
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-160,68,-67), Chunk: (at 0,4,13 in -10,-5; contains blocks -160,0,-80 to -145,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3053400 game time, 3436437 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 96288 (now: false), thunder time: 107289 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 694573648 bytes (662 MB) / 5662310400 bytes (5400 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.45.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.45
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 DONE}
		strawgolem-1.15.2-1.9.jar Straw Golem {strawgolem@1.15.2-1.9 DONE}
		essentials-1.15.2-2.7.4.jar Essentials {essentials@1.15.2-2.7.4 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		NamePain-1.3.0_Forge-1.15.2.jar Name Pain {namepain@1.3.0 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		PackMenu-1.15.2-1.2.8.jar Pack Menu {packmenu@1.2.8 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE} 
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.6.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 DONE}
		SilentGear-1.15.2-1.11.3+160.jar Silent Gear {silentgear@1.11.3+160 DONE}
		simplefarming-1.15.2-1.3.3.jar Simple Farming {simplefarming@1.15.1-1.3.3 DONE}
		MysticalAdaptations-1.15.2-1.2.3.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 DONE}
		NaturesAura-28.5.jar Nature's Aura {naturesaura@28.5 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.3.10.jar The Bumblezone {the_bumblezone@1.15.2-1.3.10 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		mining-helmet-1.15.2-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		FallingTree-1.15.2-2.4.0.jar Falling Tree {falling_tree@2.4.0 DONE}
		fishtraps-forge-1.15.2-0.0.5.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		KiwiBirds 1.3 1.15.2.jar Kiwi Birds {kiwibirds@1.2 1.15.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.6.0.jar Fruit Trees {fruittrees@1.6.0 DONE}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 DONE}
		VanillaTweaks-1.15.2.1.5.30.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.30 DONE}
		DefaultSettings-1.14.x-1.15.2-2.2.0.jar DefaultSettings {defaultsettings@2.2.0 DONE}
		betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 DONE}
		JAOPCA-1.15.2-3.2.0.15.jar JAOPCA {jaopca@3.2.0.15 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-3.11m.jar Performant {performant@3.11m DONE}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		Aquaculture-1.15.2-2.0.21.jar Aquaculture 2 {aquaculture@1.15.2-2.0.21 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['MariusNinjai'/297, l='King', x=-229.87, y=68.45, z=-4.36]]
	Data Packs: vanilla, inmemory:jaopca (incompatible), mod:netherportalfix (incompatible), mod:refinedpipes, mod:doggytalents (incompatible), mod:mcwwindows, mod:silents_mechanisms (incompatible), mod:industrialagriculture (incompatible), mod:strawgolem, mod:essentials (incompatible), mod:placebo (incompatible), mod:namepain, mod:theloader (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:buildinggadgets (incompatible), mod:progressivebosses, mod:mcwdoors, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:snowrealmagic, mod:refinedstorage (incompatible), mod:packmenu (incompatible), mod:mcwbridges, mod:usefulbackpacks, mod:ambientsounds (incompatible), mod:iapsm (incompatible), mod:biomesoplenty, mod:phosphor, mod:blur (incompatible), mod:valhelsia_structures (incompatible), mod:mining_dimension, mod:silentgear (incompatible), mod:simplefarming, mod:mysticaladaptations (incompatible), mod:mysticalagradditions, mod:curios (incompatible), mod:patchouli (incompatible), mod:cloth-config2 (incompatible), mod:oreexcavation (incompatible), mod:libnonymous (incompatible), mod:elevatorid, mod:obfuscate (incompatible), mod:naturesaura (incompatible), mod:cfm (incompatible), mod:aiimprovements (incompatible), mod:mcwfurnitures, mod:the_bumblezone, mod:fastleafdecay, mod:inventorysorter (incompatible), mod:cucumber, mod:mining_helmet (incompatible), mod:jei (incompatible), mod:falling_tree, mod:fishtraps (incompatible), mod:abnormals_core, mod:buzzierbees, mod:kiwibirds, mod:goblintraders, mod:mekanism, mod:waystones (incompatible), mod:goldenhopper, mod:lightoverlay-forge (incompatible), mod:journeymap (incompatible), mod:naturescompass (incompatible), mod:fruittrees, mod:kiwi, mod:vanillatweaks, mod:defaultsettings (incompatible), mod:betteranimalsplus (incompatible), mod:snowundertrees (incompatible), mod:bonsaitrees2, mod:jeitweaker, mod:crafttweaker (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:waddles (incompatible), mod:mysticalagriculture, mod:ironchest, mod:craftingtweaks (incompatible), mod:endergetic (incompatible), mod:swingthroughgrass (incompatible), mod:mousetweaks (incompatible), mod:silentlib (incompatible), mod:morevanillalib, mod:jaopca (incompatible), mod:gravestone, mod:autumnity, mod:autoreglib (incompatible), mod:quark, mod:storagedrawers (incompatible), mod:performant (incompatible), mod:vanillahammers, mod:midnight, mod:pickletweaks, mod:appleskin (incompatible), mod:aquaculture, mod:iapmekanism, mod:refinedstorageaddons (incompatible), mod:solargeneration, mod:soundfilters (incompatible), the_loader/SGear-Basic-Metals-v1.3.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by DarkWolfe5** [comment]
If you have serene seasons installed, I had similar problems. I moved to a warmer biome (plains) and it worked.

**Comment by Ellpeck** [comment]
Try to reproduce this without any other mods installed. If it doesn't happen, please try to figure out which mod causes it.

**Comment by Ellpeck** [comment]
Closing this, as 1.15 isn't supported anymore and this issue is stale.
