### ISSUE TITLE
Nature's Aura Tutorial Book Rendering Issue

### ISSUE THREAD

**Issue by Rumshum** [Ellpeck/NaturesAura#238]
Anytime the tutorial book is open it doesn't display any written text or ritual help with the usual phantom blocks. It only directs me to my most recent log with a runtime exception error loading page 5 specifically? I included what I think is the whole error and then the actual log file at the bottom if it helps
`[09:17:32] [main/ERROR]: Error while loading contents for book naturesaura:book
java.lang.RuntimeException: Error building entry naturesaura:using/altar
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.BookContents$$Lambda$58230/144608994.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:972) ~[?:1.8.0_51]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) [?:1.16.4-53.2]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) [?:1.16.4-53.2]
	at vazkii.patchouli.common.book.BookRegistry$$Lambda$58220/1421570436.accept(Unknown Source) [?:1.16.4-53.2]
	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_51]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) [?:1.16.4-53.2]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) [?:1.16.4-53.2]
	at vazkii.patchouli.client.base.ClientProxy.requestBookReload(ClientProxy.java:39) [?:1.16.4-53.2]
	at vazkii.patchouli.common.base.PatchouliAPIImpl.reloadBookContents(PatchouliAPIImpl.java:125) [?:1.16.4-53.2]
	at com.github.klikli_dev.occultism.network.MessageUpdatePentacles$UpdatePentacles$1.run(MessageUpdatePentacles.java:85) [?:1.16.5-1.23.7]
	at com.github.klikli_dev.occultism.network.MessageUpdatePentacles.onClientReceived(MessageUpdatePentacles.java:74) [?:1.16.5-1.23.7]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.handleClient(OccultismPacketHandler.java:57) [?:1.16.5-1.23.7]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.lambda$handle$1(OccultismPacketHandler.java:43) [?:1.16.5-1.23.7]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler$$Lambda$58219/1781168452.run(Unknown Source) [?:1.16.5-1.23.7]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) [?:?]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.handle(OccultismPacketHandler.java:42) [?:1.16.5-1.23.7]
	at com.github.klikli_dev.occultism.network.OccultismPackets$$Lambda$40992/591348772.accept(Unknown Source) [?:1.16.5-1.23.7]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$56507/1652916629.accept(Unknown Source) [?:?]
	at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2822/185324903.accept(Unknown Source) [?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2824/1594623186.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3206/1495319789.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$56495/1540356945.apply(Unknown Source) [?:?]
	at java.util.Optional.map(Optional.java:215) [?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$57236/1521474810.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at com.thenatekirby.jepb.plugin.PiglinBarteringRecipeBuilder.getManager(PiglinBarteringRecipeBuilder.java:79) [?:1.0.0]
	at com.thenatekirby.jepb.plugin.PiglinBarteringRecipeBuilder.getPiglinBarteringRecipes(PiglinBarteringRecipeBuilder.java:41) [?:1.0.0]
	at com.thenatekirby.jepb.plugin.JEPBPlugin.registerRecipes(JEPBPlugin.java:37) [?:1.0.0]
	at mezz.jei.load.PluginLoader.lambda$new$5(PluginLoader.java:117) [?:7.7.1.138]
	at mezz.jei.load.PluginLoader$$Lambda$57928/973388641.accept(Unknown Source) [?:7.7.1.138]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:7.7.1.138]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:117) [?:7.7.1.138]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) [?:7.7.1.138]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.138]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.138]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.138]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$49229/888247146.accept(Unknown Source) [?:7.7.1.138]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2824/1594623186.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3206/1495319789.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:786) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$57236/1521474810.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/1980783296.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry naturesaura:using/altar page 5
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-53.2]
	... 87 more
Caused by: java.lang.RuntimeException: Unknown item ID: naturesaura:altar
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:82) ~[?:1.16.4-53.2]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackListFromString(ItemStackUtil.java:132) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromNonArray(ItemStackArrayVariableSerializer.java:37) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromJson(ItemStackArrayVariableSerializer.java:29) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromJson(ItemStackArrayVariableSerializer.java:14) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:31) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.component.ComponentItemStack.onVariablesAvailable(ComponentItemStack.java:38) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.VariableAssigner.assignVariableHolders(VariableAssigner.java:46) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.TemplateComponent.compile(TemplateComponent.java:49) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:112) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16.4-53.2]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-53.2]
	... 87 more`
[latest.log](https://github.com/Ellpeck/NaturesAura/files/7835421/latest.log)

**Comment by Ellpeck** [comment]
Please try to recreate this issue without any other mods (other than Patchouli) installed.

**Comment by pafeuu** [comment]
Not sure If should type here or create a new issue but im pretty sure I found the cause at least for my case.
Changing the recipe of gold powder (probably not just that but its the one I tested it with) with kubejs makes the book not render stuff at all, probably because there are already recipes shown for that in the book. Is there anything you can do to fix that?

**Comment by Ellpeck** [comment]
You need to name the recipe the same as the old recipe, or the book will break. Alternatively, if you do change the name of the recipe, you can create a datapack that edits the book to refer to the new recipe name. This is not a bug.

**Comment by pafeuu** [comment]
I assumed its a bug because no other guide book breaks like that but since its easy to fix I have no problem with that. Thank you for clarifying

**Comment by pafeuu** [comment]
![aura2](https://user-images.githubusercontent.com/83570585/156771076-a971af93-7845-48bc-9a02-a3a079c26a9a.png)
![aura1](https://user-images.githubusercontent.com/83570585/156771081-96d72edf-892c-41a3-978e-fa056efba3ae.png)
![aura3](https://user-images.githubusercontent.com/83570585/156771083-a9b3739a-68f1-4e87-a307-4f858a5a3397.png)
And changing the id doesn't really work, whole guide book is still broken.

**Comment by Ellpeck** [comment]
Please share the log file for this issue, thanks!

**Comment by pafeuu** [comment]
[latest.log](https://github.com/Ellpeck/NaturesAura/files/8186252/latest.log)

**Comment by Ellpeck** [comment]
This looks like an issue with Patchouli itself, and it is very similar to what @Rumshum originally reported. Please report this to the Patchouli issue tracker, and comment on this issue again (or link it) if new discoveries are made :)

As a side note, there seems to be a lot broken with your pack in terms of loot tables and recipes. You might want to check that out!
