### ISSUE TITLE
[1.20.4 NeoForge] server not starting

### ISSUE THREAD

**Issue by MSandro** [Ellpeck/NaturesAura#346]
```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-03-25 16:20:27
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[neoforge-20.4.211-universal.jar%23131!/:?] {re:classloading}
	at net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[neoforge-20.4.211-universal.jar%23131!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:122) ~[server-1.20.4-20231207.154220-srg.jar%23130!/:?] {re:classloading}
...
```

**Comment by Ellpeck** [comment]
It looks like you don't have Patchouli installed. It's a required dependency of Nature's Aura :)

**Comment by MSandro** [comment]
this is my current mod list:
```
cloth-config-13.0.121-neoforge.jar
curios-neoforge-7.3.4+1.20.4.jar
geckolib-neoforge-1.20.4-4.4.4.jar
Jade-1.20.4-neoforge-13.3.1.jar
jei-1.20.4-neoforge-17.3.0.49.jar
Modern-Industrialization-2.0.17-alpha-all.jar
NaturesAura-40.0.jar
```
Modern-Industrialization has embedded Patchouli.
I have no idea where to get Patchouli for neoforge else where.

but now I get this crash:
```
...
[09:43:02] [main/ERROR] [ne.ne.fm.co.as.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[09:43:02] [main/ERROR] [ne.ne.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        Index: 0
        Listeners:
                0: net.neoforged.bus.EventListenerFactory$onPayloadRegister/0x00007f4760bb4800@6569268a
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at TRANSFORMER/naturesaura@40.0/de.ellpeck.naturesaura.packet.PacketHandler.onPayloadRegister(PacketHandler.java:22)
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:386)
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:365)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:210)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.lambda$postEvent$29(ModLoader.java:346)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:231)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:346)
        at TRANSFORMER/neoforge@20.4.211/net.neoforged.neoforge.network.registration.NetworkRegistry.setup(NetworkRegistry.java:122)
        at TRANSFORMER/neoforge@20.4.211/net.neoforged.neoforge.internal.NeoForgeStatesProvider.lambda$new$5(NeoForgeStatesProvider.java:23)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.handleInlineTransition(ModLoader.java:225)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:217)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.dispatchAndHandleError(ModLoader.java:217)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.lambda$finishMods$17(ModLoader.java:205)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.ModLoader.finishMods(ModLoader.java:205)
        at TRANSFORMER/neoforge@20.4.211/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.Main.main(Main.java:122)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26)
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[09:43:02] [main/ERROR] [ne.ne.fm.ModContainer/LOADING]: Caught exception during event net.neoforged.neoforge.network.event.RegisterPayloadHandlerEvent@75001f9f dispatch for modid naturesaura
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191) ~[securejarhandler-2.1.24.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at de.ellpeck.naturesaura.packet.PacketHandler.onPayloadRegister(PacketHandler.java:22) ~[NaturesAura-40.0.jar%23136!/:?] {re:classloading}
        at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%2370!/:?] {}
        at net.neoforged.bus.EventBus.post(EventBus.java:365) ~[bus-7.2.0.jar%2370!/:?] {}
        at net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:210) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$postEvent$29(ModLoader.java:346) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.neoforged.fml.ModList.forEachModInOrder(ModList.java:231) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.postEvent(ModLoader.java:346) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.neoforge.network.registration.NetworkRegistry.setup(NetworkRegistry.java:122) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.neoforged.neoforge.internal.NeoForgeStatesProvider.lambda$new$5(NeoForgeStatesProvider.java:23) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.neoforged.fml.ModLoader.handleInlineTransition(ModLoader.java:225) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:217) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.neoforged.fml.ModLoader.dispatchAndHandleError(ModLoader.java:217) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$finishMods$17(ModLoader.java:205) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.neoforged.fml.ModLoader.finishMods(ModLoader.java:205) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:122) ~[server-1.20.4-20231207.154220-srg.jar%23138!/:?] {re:classloading}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
[09:43:02] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: NaturesAura (naturesaura) encountered an error during the done event phase
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:214) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$postEvent$29(ModLoader.java:346) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.neoforged.fml.ModList.forEachModInOrder(ModList.java:231) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.postEvent(ModLoader.java:346) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.neoforge.network.registration.NetworkRegistry.setup(NetworkRegistry.java:122) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.neoforged.neoforge.internal.NeoForgeStatesProvider.lambda$new$5(NeoForgeStatesProvider.java:23) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.neoforged.fml.ModLoader.handleInlineTransition(ModLoader.java:225) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:217) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.neoforged.fml.ModLoader.dispatchAndHandleError(ModLoader.java:217) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.ModLoader.lambda$finishMods$17(ModLoader.java:205) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.neoforged.fml.ModLoader.finishMods(ModLoader.java:205) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-20.4.211-universal.jar%23139!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:122) ~[server-1.20.4-20231207.154220-srg.jar%23138!/:?] {re:classloading}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191) ~[securejarhandler-2.1.24.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at de.ellpeck.naturesaura.packet.PacketHandler.onPayloadRegister(PacketHandler.java:22) ~[NaturesAura-40.0.jar%23136!/:?] {re:classloading}
        at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%2370!/:?] {}
        at net.neoforged.bus.EventBus.post(EventBus.java:365) ~[bus-7.2.0.jar%2370!/:?] {}
        at net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:210) ~[loader-2.0.17.jar%2362!/:2.0] {}
        ... 29 more

```

**Comment by Ellpeck** [comment]
Ah, now this looks like a Nature's Aura bug.
