### ISSUE TITLE
Disconnected from server when sneaking while Aura Cache or Aura Trove is in inventory

### ISSUE THREAD

**Issue by 12snooper12** [Ellpeck/NaturesAura#371]
Reproduced this issue several times testing different combinations of other items equipped and keybinds etc.
If the Cache/Trove is empty it's fine but fully or partially filled will trigger it.

Log from server hosting ATM10 1.15, NeoForge 21.1.73, NaturesAura 41.3. Internal server error and player is disconnected.

[03Nov2024 14:44:57.767] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@6d420cdd
[03Nov2024 14:44:57.767] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@378fd1ac
[03Nov2024 14:44:57.789] [Server thread/ERROR] [net.minecraft.CrashReport/]: Negative index in crash report handler (0/10)
[03Nov2024 14:44:57.789] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /[::1]:63099
net.minecraft.ReportedException: Ticking player
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:625) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:260) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.tick(Connection.java:412) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:159) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1051) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
[03Nov2024 14:44:57.800] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: snooper12 lost connection: Internal server error
[03Nov2024 14:44:57.800] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: snooper12 left the game

**Comment by Ellpeck** [comment]
Hi, thanks so much for your report! It'd be very useful if you could also try reproducing this issue with just Nature's Aura and Patchouli installed :)

**Comment by 12snooper12** [comment]
Thanks for the quick response :)

I tested on a clean instance with just neoforge, patchouli and Nature's Aura installed and it worked fine, however just to cover my bases I tried a singleplayer world on ATM10 and that also worked fine, even when "open to lan" is enabled.

I'm not technical enough to host a headless server with just those mods installed to do a true test I'm afraid.
