### ISSUE TITLE
Exception on first world loading

### ISSUE THREAD

**Issue by AssB0ys** [Ellpeck/NaturesAura#45]
This error appears when you first create and load into a world.
` 
[13:55:46] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@11c26f3d:
java.lang.NullPointerException: null
	at de.ellpeck.naturesaura.api.aura.type.BasicAuraType.isPresentInWorld(BasicAuraType.java:38) ~[BasicAuraType.class:?]
	at de.ellpeck.naturesaura.api.aura.type.IAuraType.forWorld(IAuraType.java:12) ~[IAuraType.class:?]
	at de.ellpeck.naturesaura.events.CommonEvents.onChunkCapsAttach(CommonEvents.java:31) ~[CommonEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_120_CommonEvents_onChunkCapsAttach_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:685) [ForgeEventFactory.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:94) [axw.class:?]
	at net.optifine.util.ChunkUtils.findFieldHasEntities(ChunkUtils.java:58) [ChunkUtils.class:?]
	at net.optifine.util.ChunkUtils.<clinit>(ChunkUtils.java:22) [ChunkUtils.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1397) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1731) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[13:55:46] [Client thread/ERROR] [FML]: Index: 2 Listeners:
[13:55:46] [Client thread/ERROR] [FML]: 0: NORMAL
[13:55:46] [Client thread/ERROR] [FML]: 1: ASM: class com.cazsius.solcarrot.handler.CapabilityHandler attachPlayerCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/ERROR] [FML]: 2: ASM: de.ellpeck.naturesaura.events.CommonEvents@5f4452bb onChunkCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/ERROR] [FML]: 3: ASM: de.ellpeck.naturesaura.events.CommonEvents@5f4452bb onWorldCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/ERROR] [FML]: 4: ASM: net.mcft.copy.backpacks.ProxyClient@40487b38 onAttachCapabilitiesEntity(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/ERROR] [FML]: 5: ASM: c4.comforts.common.capability.CapabilitySleepTime$EventHandler@17073c7a attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/ERROR] [FML]: 6: ASM: c4.comforts.common.capability.CapabilitySleeping$EventHandler@46c1e826 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[13:55:46] [Client thread/WARN] [Config]: [OptiFine] java.lang.NullPointerException null
[13:55:46] [Client thread/WARN] [Config]: [OptiFine] Error finding Chunk.hasEntities
`

This happens when optifine is installed. I tried combinations of optifines latest preview 1.12.2 HD U E4 pre4(a), current stable 1.12.2 HD U E3(b) with forge latest 1.12.2 - 14.23.5.2835(i), current stable 1.12.2 - 14.23.5.2768(j) and optifine recommended 1.12.2 - 14.23.5.2795(k) versions.(like this: a+i, a+j, a+k, b+i, b+j, b+k). It happens on any combination.

Now when I exit the world and load the world again, no such error appear in the log and I haven't experienced any crashes(just yet). I don't want to some day find my world corrupted after putting some time into it and it would be good if you looked into it or at least explained to me if this a serious problem or not, what steps should I take next. Thank you.

full log at: https://pastebin.com/JgvnzyUS

**Comment by Ellpeck** [comment]
Does this issue also happen without OptiFine?

**Comment by AssB0ys** [comment]
No it doesn't. No errors appear in the log related to natures aura mod. I have to use optifine otherwise my fps drops severely.
I couldn't make much sense from the error in the log, I just suppose that some of the features fail to load(initialize or I don't know the correct terminology). But as i stated before, I want to know if this is a critical issue and a potential cause for problems in the long run.

**Comment by AssB0ys** [comment]
So what exactly is this fix? Does it add a delay to the initialization(i don't know if this is correct word, because I don't know what is this error related to internally) or disallows some of the mods features? I just want to know if, for example, creating the world and then reentering it would be correct steps to avoid this? As the error only appears on the first freshly created world load.

**Comment by Ellpeck** [comment]
this just causes the exception not to occur. I don't know if it causes any issues in the long run.

**Comment by AssB0ys** [comment]
Alright, I'll have to look out for this then. And I will report if I encounter any problems. Thanks for the quick reply.

**Comment by Ellpeck** [comment]
It looks like this is a one-time thing that OptiFine does to gather some data (presumably to improve performance somewhere later down the line). It really shouldn't have an effect on the overall gameplay.
