### ISSUE TITLE
Server crash on using powder of fertility

### ISSUE THREAD

**Issue by AhSchoo** [Ellpeck/NaturesAura#86]
In Just Not Enough Mods 2 ver 0.5.0

After placing powder of fertility.
java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.func_174872_o()I
	at de.ellpeck.naturesaura.chunk.effect.AnimalEffect.update(AnimalEffect.java:87) ~[?:23.1] {re:classloading}
	at de.ellpeck.naturesaura.chunk.AuraChunk.update(AuraChunk.java:151) ~[?:23.1] {re:classloading}
	at de.ellpeck.naturesaura.events.CommonEvents.onWorldTick(CommonEvents.java:64) ~[?:23.1] {re:classloading}

**Comment by Ellpeck** [comment]
What Minecraft, Forge and Nature's Aura version?

**Comment by AhSchoo** [comment]
forge-1.15.2-31.1.18  
NaturesAura-23.1
